steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/ace-line-434711-d7/gke-repo/quickstart-image', '.' ]
  id: 'Build Docker Image'
  options:
  logging: CLOUD_LOGGING_ONLY  
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/ace-line-434711-d7/gke-repo/quickstart-image' ]
  id: 'Push Docker Image'
